apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: otel-lab
type: Opaque
stringData:
  POSTGRESQL_USER: oteluser
  POSTGRESQL_PASSWORD: otelpass
  POSTGRESQL_DATABASE: oteldemo